<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice Rule</name>
  <uuid>86d1c4ab-14bb-4cc6-b303-3ead4cc5964b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is not empty 
then
	set decision to `Hello { Name }!`;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
